# Generated by Django 6.1 on 2026-08-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(max_length=10)),
                ('guardian_full_name', models.CharField(max_length=100)),
                ('guardian_contact_number', models.CharField(max_length=13)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('learning_difficulty_category', models.CharField(max_length=30)),
                ('consent_given', models.BooleanField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
